server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 1. Auth Service (يمرر /api/auth كما هي لكود Express)
    location /api/auth {
        proxy_pass http://auth-service:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Booking Service (مطابق لطلب الفرونت /bookings)
    location /bookings {
        proxy_pass http://booking-service:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 3. Catalog Service (مطابق لطلب الفرونت /events)
    location /events {
        proxy_pass http://catalog-service:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}