FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN chmod +x node_modules/.bin/vite
RUN npm run build
RUN npm install -g http-server
EXPOSE 80
CMD ["http-server", "dist", "-p", "80"]